- name: download docker-compose
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/v{{docker_compose_installation_docker_compose_version}}/docker-compose-{{ansible_facts['system']|lower}}-{{ansible_facts['architecture']}}"
    dest: /usr/local/bin/docker-compose
    mode: "0555"
